# Generated by Django 5.2.7 on 2025-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_brand_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1234, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('cash', 'Cash on Delivery')], default='card', max_length=20),
        ),
    ]
